language: ruby
bundler_args: --without development
script:
  - bundle install
  - rake db:create
  - rake db:migrate
  - rake db:test:prepare
  - rake spec
  - rake cucumber
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile
notifications:
  recipients:
    - para.alves@gmail.com
branches:
  only:
    - master
