language: ruby
bundler_args: --without development
script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
  - bundle exec rake cucumber
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile
notifications:
  recipients:
    - para.alves@gmail.com
branches:
  only:
    - master
