language: ruby
bundler_args: --without production development
before_script:
script:
  - bundle exec rake db:setup
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
  - bundle exec rake cucumber
rvm:
  - 1.8.7
  - rbx-19mode
  - jruby-19mode
  - jruby-head
  - 1.9.2
  - 1.9.3
gemfile:
  - Gemfile
notifications:
  recipients:
    - para.alves@gmail.com
branches:
  only:
    - master
