language: ruby
bundler_args: --without production development
before_script:
script:
  - bundle exec rake db:setup
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
  - bundle exec rake cucumber
rvm:
  - 2.0.0
gemfile:
  - Gemfile
notifications:
  recipients:
    - para.alves@gmail.com
branches:
  only:
    - master
