development:
  adapter: postgresql
  database: crawler_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: crawler_test
  host: localhost
  pool: 5

production:
 adapter: postgresql
 encoding: unicode
 database: room_production
 pool: 5
 password: admin